name: Pac-Man Contribution Graph

on:
  # Schedule the workflow to run weekly on Sundays at midnight UTC
  schedule:
    - cron: "0 0 * * 0"
  # Allow manual triggering of the workflow
  workflow_dispatch:
  # Trigger the workflow on pushes to the main branch
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      # Step 2: Generate the Pac-Man contribution graph
      - name: Generate Pac-Man contribution graph
        run: |
          curl -s https://raw.githubusercontent.com/Platane/snk/master/snk() | bash -s -- -u ${{ github.repository_owner }}

      # Step 3: Commit and push the generated Pac-Man graph to the 'output' folder
      - name: Commit and Push Pac-Man Contribution Graph
        run: |
          git add output/pacman-contribution-graph.svg
          git commit -m "Update Pac-Man contribution graph"
          git push

      # Step 4: Deploy the generated file to the 'output' branch
      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: output
          commit_message: "Update Pac-Man contribution graph [skip ci]"
